# Numpy
https://docs.scipy.org/doc/numpy-1.13.0/reference/

In [1]:
import numpy as np

In [25]:
a = np.array([1,2,3,4])
print(a)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)

[1 2 3 4]
(4,)
int64
4
1


In [26]:
a = np.zeros((3,3), dtype=np.int8)
print(a)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)
int8
9
2


In [27]:
a = np.array([1,2,3,4], dtype=np.float64)
print(a)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)

[ 1.  2.  3.  4.]
(4,)
float64
4
1


In [45]:
a = np.array([[5,2,8], [3,9,5]])
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())
print(a.sum())
print(a.mean())
print(np.median(a))
print(a.sum(axis=0))
print(a.sum(axis=1))

2
9
1
4
32
5.33333333333
5.0
[ 8 11 13]
[15 17]
